@echo off
setlocal
title Install RCD Memo Monitoring Client
set "CLIENTDIR=%LocalAppData%\RCD Memo Monitoring Client"
if not exist "%CLIENTDIR%" mkdir "%CLIENTDIR%"
copy /Y "%~dp0OPEN_RCD_MEMO_APP.cmd" "%CLIENTDIR%\OPEN_RCD_MEMO_APP.cmd" >nul
if not exist "%~dp0server-url.txt" (
  echo ERROR: server-url.txt is missing.
  echo Use the client folder generated by INSTALL_SERVER.bat on the server computer.
  pause
  exit /b 1
)
copy /Y "%~dp0server-url.txt" "%CLIENTDIR%\server-url.txt" >nul
copy /Y "%~dp0assets\ORCD-MEMO-ICON.ico" "%CLIENTDIR%\ORCD-MEMO-ICON.ico" >nul
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0scripts\create-client-shortcut.ps1" -ClientFolder "%CLIENTDIR%"
echo.
echo Client installed. Use the RCD Memo Monitoring System shortcut on your Desktop.
set /p SERVER_URL=<"%~dp0server-url.txt"
echo Server address: %SERVER_URL%
echo.
pause
