#:schema node_modules/wrangler/config-schema.json
name = "memo-monitoring-system"
compatibility_date = "2024-09-23"

# Cloudflare Static Assets Serving for Workers & Pages
[assets]
directory = "."
binding = "ASSETS"

# Cloudflare Environment Variables
[vars]
ENVIRONMENT = "production"
SYSTEM_TITLE = "RCD Memorandum Monitoring System (PRO 4A)"
