#:schema node_modules/wrangler/config-schema.json
name = "rcd-memo-monitoring-system"
compatibility_date = "2024-09-23"

# Cloudflare Pages output directory
pages_build_output_dir = "."

# Cloudflare Pages Environment Variables
[vars]
ENVIRONMENT = "production"
SYSTEM_TITLE = "RCD Memorandum Monitoring System (PRO 4A)"
